# Configuration for my production environment

services:
  migrations:
    image: ghcr.io/aikenahac/mwh:beta
    container_name: mwh-migrations
    pull_policy: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mwh
    command: sh -c "pnpm db:push"
    restart: "no"

  app:
    image: ghcr.io/aikenahac/mwh:master
    container_name: mwh
    pull_policy: always
    env_file:
      - .env
    ports:
      - "3101:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mwh

  # app-beta:
  #   image: ghcr.io/aikenahac/mwh:beta
  #   container_name: mwh-beta
  #   pull_policy: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "3102:3000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   networks:
  #     - mwh

  studio:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: mwh-db-studio
    environment:
      - PORT=4983

      - MASTERPASS=${DRIZZLE_MASTERPASS}
    volumes:
      - drizzle_gateway:/app
    restart: unless-stopped
    networks:
      - mwh

  db:
    image: postgres:latest
    container_name: mwh-db
    env_file:
      - .env
    volumes:
      - mwh_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
       - mwh

volumes:
  mwh_db_data:
  drizzle_gateway:

networks:
  mwh:
    driver: bridge
